---
Description: >
  Udacity 2019 - Devops Nanodegree - Capstone Project
  Code for EC2 instance with Jenkins.
Parameters:
  Capstone:
    Description: Enviroment name 
    ConstraintDescription: Invalid name. Please, choose one from the list
    Type: String
    AllowedValues:
      - Development 
      - Staging 
      - Production 
  SourceIP:
    Description: Ip address to allow SSH access to the bastion host
    Type: String
    Default: IP/32

  KeyJenkinsSSH:
    Description: Jenkins KeyName 
    Type: "AWS::EC2::KeyPair::KeyName"

Mappings:
  CapstoneRegion:
    eu-west-1:
      HVM64: ami-0d5d9d301c853a04a

Resources:
  CapstoneSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH access to EC2
      VpcId:
        Fn::ImportValue: !Sub "${Capstone}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub ${SourceIP}
      Tags:
        - Key: Name
          Value: !Sub ${Capstone}-WASG

  CapstoneEc2:
    Type: AWS::EC2::Instance
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt-get update -y
          sudo apt-get install default-jdk wget -y
          cd /home/ubuntu
          wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
          sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
          sudo apt-get update -y
          sudo apt-get install jenkins tidy -y
          sudo systemctl status jenkins
      SecurityGroupIds:
        - Ref: CapstoneSG
      SubnetId:
        Fn::ImportValue: !Sub "${Capstone}-SUBNET1"
      BlockDeviceMappings:
        - DeviceName: "/dev/sdk"
          Ebs:
            VolumeSize: "10"
            DeleteOnTermination: true
            VolumeType: "gp2"
      ImageId: !FindInMap [CapstoneRegion, !Ref "AWS::Region", HVM64]
      InstanceType: t3.small
      KeyName: !Sub ${KeyJenkinsSSH}
  
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain:
        Fn::ImportValue: !Sub "${Capstone}-VPCID"

  EIPAssociation0:
    Type: AWS::EC2::EIPAssociation
    DependsOn:
      - CapstoneEc2
      - EIP
    Properties:
      InstanceId:
        Ref: CapstoneEc2
      AllocationId:
        Fn::GetAtt:
          - EIP
          - AllocationId

Outputs:
  Website:
    Description: Public DNS for EC2 Instance
    Value: !Join ['', ['http://', !GetAtt 'CapstoneEc2.PublicDnsName', ':8080']]
